name: build

on:
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'go.mod'
      - 'go.sum'
      - '*.go'
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'go.mod'
      - 'go.sum'
      - '*.go'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPROXY: https://goproxy.io
    strategy:
      matrix:
        go:
          - 1.11.x
          - 1.12.x
          - 1.13.x
    steps:
      -
        # https://github.com/actions/setup-go
        name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go }}
      -
        name: Cache Go modules
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Test
        run: |
          go env
          go test -coverprofile=coverage.txt -covermode=atomic ./...
      -
        # https://github.com/codecov/codecov-action
        name: Upload coverage
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
