name: build

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x]
    steps:
      -
        # https://github.com/actions/setup-go
        name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go }}
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Test
        run: |
          go test -race -v ./...
