name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

env:
  DESTDIR: ./bin
  DOCKER_BUILD_SUMMARY: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Lint
        uses: docker/bake-action@d3418bd7d0e9324001bca92fa8ba175ea7e6dc9b # v7.3.0
        with:
          targets: lint

  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.24"
          - "1.25"
    steps:
      -
        name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      -
        name: Test
        uses: docker/bake-action@d3418bd7d0e9324001bca92fa8ba175ea7e6dc9b # v7.3.0
        with:
          source: .
          targets: test
        env:
          GO_VERSION: ${{ matrix.go }}
      -
        name: Upload coverage
        if: ${{ matrix.go == '1.25' }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          directory: ${{ env.DESTDIR }}/coverage
          token: ${{ secrets.CODECOV_TOKEN }}
